### ISSUE TITLE
Upload not working 

### ISSUE THREAD

**Issue by razzbee** [j0k3r/php-imgur-api-client#11]
Hello , I am trying to upload to Imgur account , but it seems not working, I dont get any error code too.This is the call back returned  : 

```
Basic {#223 ▼
  -data: []
  -success: false
  -status: null
}

```

**Comment by j0k3r** [comment]
Could you share the code you are using?

**Comment by j0k3r** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
