### ISSUE TITLE
Update to Guzzle 6

### ISSUE THREAD

**Issue by xandros15** [j0k3r/php-imgur-api-client#14]
Is there any chance to update this project to guzzle 6?

**Comment by j0k3r** [comment]
I just updated it to Guzzle 5 atm.
I plan to try if I can let them run together without breaking everything.

**Comment by j0k3r** [comment]
Could you try using the 3.x branch? It should be ok with Guzzle 6. Let me know.

**Comment by xandros15** [comment]
I needed this asap so I create somthing on my own: 
https://github.com/xandros15/aigisu/blob/new-system/src/components/imgur/Client.php
In my future projects I will use your solution.

**Comment by j0k3r** [comment]
Ok thanks, I can close that issue then.
