### ISSUE TITLE
Add support for "token" as authorization response type

### ISSUE THREAD

**Issue by AlfredoRamos** [j0k3r/php-imgur-api-client#26]
Currently `pin` and `code` are deprecated according to the [Imgur docs](https://apidocs.imgur.com/#authorization-and-oauth):

> The `code` and `pin` response types have been deprecated and will soon no longer be supported

And the library does not accept the new `token` for `response_type`:

https://github.com/j0k3r/php-imgur-api-client/blob/627a68515da67bf8aa1cf89c3dce7ca77ce287ae/lib/Imgur/Auth/OAuth2.php#L105-L117

I've been lately receiving HTTP 500 responses from Imgur, I'm not sure if that's because of that API change.

**Comment by j0k3r** [comment]
Why did you close the issue? 🤔

**Comment by AlfredoRamos** [comment]
I no longer use this library.
