### ISSUE TITLE
Not returning images when is an album

### ISSUE THREAD

**Issue by ricardofiorani** [j0k3r/php-imgur-api-client#4]
When fetching frontpage gallery images, if 'isAlbum' is true it returns null in 'images'. Still, it can return the count of images inside the album.

**Comment by j0k3r** [comment]
Could you give an Imgur id or something so we can reproduce the bug?

**Comment by ricardofiorani** [comment]
I've made a gist reproducing the problem.

https://gist.github.com/ricardofiorani/30a2ea848a44581a212a

I may check this out and try to fix it later and then make a pull request if it's easy to fix...

**Comment by j0k3r** [comment]
Could you please give a try using the 2.x branch instead?

**Comment by j0k3r** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
