### ISSUE TITLE
Check if ID is image or album?

### ISSUE THREAD

**Issue by g6807937** [j0k3r/php-imgur-api-client#6]
Is it possible to check if a given ID is an image or album? How else would I know to use `image($imageId)` or `album($albumId)` without first knowing that?

**Comment by Prefinem** [comment]
I believe if you use the album api call, one of the results is 'is_album' if it is actually an album

**Comment by g6807937** [comment]
@Prefinem Not that I can see:

https://api.imgur.com/models/album

**Comment by Prefinem** [comment]
Easiest way is to call both and if one fails, use the other.  A simple if check should suffice.

**Comment by j0k3r** [comment]
I'll try to implement something like that in the 2.0.0 :+1:
