### ISSUE TITLE
getGifv() for images?

### ISSUE THREAD

**Issue by g6807937** [j0k3r/php-imgur-api-client#7]
I noticed that the imgur model for [image](https://api.imgur.com/models/image/) has a lot more properties than those I see provided in this library, like `gifv`, `mp4`, `webm`, etc.

How can I retrieve these properties using this library?

**Comment by j0k3r** [comment]
Thanks for telling us about that (_I'm the new owner of the repo, this can explain the delay in the answer_).

I'm currently rewriting the client and Models will be removed so you'll retrieve the whole response from Imgur directly.
You can check what's going on the `master` and/or `tests` branches.
