### ISSUE TITLE
Comment model need updated.

### ISSUE THREAD

**Issue by billmalarky** [j0k3r/php-imgur-api-client#9]
"Caption" references should be updated to "Comment" in Comment model. Also, non-existent function setComments() needs updated to setChildren().

[Imgur has recently renamed "captions" to the better suited term "comments."](https://api.imgur.com/models/comment) This would be a benign issue, except they have updated their API response parameter from "caption" to "comment" which breaks this API client.

Additionally, the Comment model references a function that doesn't actually exist, setComments(). The actual function name which accomplishes the desired effect is setChildren().

For a patch, please look at [my fork's commit here](https://github.com/billmalarky/php-imgur-api-client/commit/74fe82fda9842568e82cc94ac8e183bc8aae0fa9).

I forked instead of issuing pull request because I need this working tonight, and also I'm building some custom functions into this library as well.

Thanks for building this.

**Comment by j0k3r** [comment]
Thanks for telling us about that (_I'm the new owner of the repo, this can explain the delay in the answer_).
Feel free to submit a PR to fix that (on the 1.x branch).

I'm currently rewriting the client and Models will be removed.
You can check what's going on the `master` and/or `tests` branches.
